### ISSUE TITLE
Problems running the run_test.py

### ISSUE THREAD

**Issue by trexob1t** [uzh-rpg/dagr#8]
When attempting to run the run_test_1.py script, an AssertionError is encountered. I followed the guidelines provided in the [DSEC-Detection](https://github.com/uzh-rpg/dsec-det?tab=readme-ov-file#test-alignment) to download, so I am uncertain why this error is occurring.

## Command executed
```
CUDA_VISIBLE_DEVICES=$DEVICE python scripts/run_test.py --config config/dagr-s-dsec.yaml --use_image --img_net resnet50 --checkpoint data/dagr_s_50.pth --batch_size 4 --dataset_directory $DSEC_ROOT --output_directory $LOG_DIR
```

## Error message

```Traceback (most recent call last):
  File "scripts/run_test_1.py", line 67, in <module>
    metrics = run_test_with_visualization(test_loader, ema.ema, dataset=args.dataset)
  File "/dagr/dagr/src/dagr/utils/testing.py", line 28, in run_test_with_visualization
    for i, data in enumerate(tqdm.tqdm(loader, desc=f"Testing {name}")):
  File "/miniconda3/envs/dagr/lib/python3.8/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/miniconda3/envs/dagr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/miniconda3/envs/dagr/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 675, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/miniconda3/envs/dagr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/miniconda3/envs/dagr/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/dagr/dagr/src/dagr/data/dsec_data.py", line 144, in __getitem__
    detections_1 = self.dataset.get_tracks(image_index_1, mask=track_masks, directory_name=dataset.root.name)
  File "/dagr/dagr/libs/dsec-det/src/dsec_det/dataset.py", line 110, in get_tracks
    i_0, i_1 = self.get_index_window(index, len(img_idx_to_track_idx), sync=self.sync)
  File "/dagr/dagr/libs/dsec-det/src/dsec_det/dataset.py", line 101, in get_index_window
    assert 0 <= index < num_idx - 1
AssertionError
```

**Comment by youkangGG** [comment]
Same error on my machine :(

**Comment by lpyQaQ** [comment]
I can run "run_test.py" successfully. However, I meet the same error when I try to run "count_flops.py".
Have you solve this problem?

**Comment by trexob1t** [comment]
@lpyQaQ unfortunately, I haven’t solved the problem. Since I only needed an event-based detection model, I switched to AEGNN, which worked out of the box for me.

**Comment by Hatins** [comment]
> I can run "run_test.py" successfully. However, I meet the same error when I try to run "count_flops.py". Have you solve this problem?

Hi, I'd like to ask you which model (ResNet18/Resnet50) do you test? and if you have got the same results provided in the paper?

**Comment by lpyQaQ** [comment]
> > I can run "run_test.py" successfully. However, I meet the same error when I try to run "count_flops.py". Have you solve this problem?
> 
> Hi, I'd like to ask you which model (ResNet18/Resnet50) do you test? and if you have got the same results provided in the paper?

I tested resnet50. And I got results as below.
![屏幕截图 2024-10-16 214030](https://github.com/user-attachments/assets/3ed348d8-8679-4b4e-968b-2242a320cea0)

**Comment by Hatins** [comment]
> > > I can run "run_test.py" successfully. However, I meet the same error when I try to run "count_flops.py". Have you solve this problem?
> > 
> > 
> > Hi, I'd like to ask you which model (ResNet18/Resnet50) do you test? and if you have got the same results provided in the paper?
> 
> I tested resnet50. And I got results as below. ![屏幕截图 2024-10-16 214030](https://private-user-images.githubusercontent.com/102471525/377077537-3ed348d8-8679-4b4e-968b-2242a320cea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNDI2OTgsIm5iZiI6MTcyOTE0MjM5OCwicGF0aCI6Ii8xMDI0NzE1MjUvMzc3MDc3NTM3LTNlZDM0OGQ4LTg2NzktNGI0ZS05NjhiLTIyNDJhMzIwY2VhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QwNTE5NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmRlNDY1Y2RlMDkxYzUxYjlmZDVkOTFhYTczMjBjZWIxMzdjMjM1MDVjMDgwNDY5OGE4OGZjNjU1YzVhNjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NWDCZSW-XahCWsdZgzvH1FyxxHMxHvNgygNhb7E-Ark)

Hi, @lpyQaQ , very thanks for your ripid reply, but it seems that the results are much lower than the results in the paper?
